### ISSUE TITLE
Error while exporting a layer

### ISSUE THREAD

**Issue by deathmaster9** [bogind/topojson_writer#1]
Error: Something went wrong with saving the TopoJson, please send us the following error: 'ascii' codec can't encode character '\xe8' in position 6: ordinal not in range(128).

Any ideas this ocured ?

**Comment by bogind** [comment]
I'm guessing you have UTF-8 or other non ascii encoded data in your layer.
This plugin was a rushed job and it seems missed adding the right encoding parameters for non ascii encoding reading.

Can you supply the full stack trace for the error? and if possible the layer you are trying to convert.
Since this seems rather minor, I might be able to get around to fixing this in the next couple of days unless you want to submit a PR before that.

**Comment by deathmaster9** [comment]
It was exactly that. By deleting non ascii characters. The export worked. My file had French data in it. Problem solved thank you for your help.
